module.exports = {
  FOURSQUARE_API_KEY: "fsq3Wy3+RUvdvcRLm4DkXbqHwQjIUUjaZcaQNxBWYjuZGhE=",
  FOURSQUARE_CLIENT_ID: "ALZER3T2IARKCQBVJQS4QAUTP5FUW2F4V5QFT5K5KWHHT1W5",
  FOURSQUARE_CLIENT_SECRET: "WLA1DLJGBNHAPAKYB5ABXOVGWWSUZDETEHVKMJ4I1CUEI5R3",
};
